server.port: 8081
spring:
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    url: jdbc:postgresql://localhost:5432/diploma
    username: admin
    password: admin
    hikari:
      schema: account
      maximum-pool-size: 6

  liquibase:
    enabled: true
grpc:
  enable-reflection: true
  port: 9091
