spring:
  main:
    banner-mode: "off"
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    url: jdbc:postgresql://localhost:5432/diploma
    username: admin
    password: admin
    hikari:
      schema: measurement
      maximum-pool-size: 6
      pool-name: MainDB-Pool
  liquibase:
    enabled: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: ${env}.measurement-service
      max-poll-records: 50

env: diploma-local

messaging:
  update-measurement:
    enabled: true
    topic: ${env}.measurement-update.proto
  event-notification:
    topic: ${env}.event-notification.proto
  update-measurement-internal:
    topic: ${env}.measurement-update-internal.proto

grpc:
  enable-reflection: true
  port: 8082