spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri:
  main:
    banner-mode: "off"
  graphql:
    path: /graphql
    websocket:
      path: /graphql

adapter:
  account:
    target: localhost:8081
    secure: false
  measurement:
    target: localhost:8082
    secure: false
  notification:
    target: localhost:8083
    secure: false
  nrfcloud:
    target: localhost:8084
    secure: false